### ISSUE TITLE
FFMPEG crashes when building a video using the full release

### ISSUE THREAD

**Issue by MalcolmMielle** [tanersener/flutter-ffmpeg#113]
**Description**
FFMPEG crash when launching a command to concatenate frames into a movie.

**Expected behavior**
A video is created

**Current behavior**
I crashes

**Screenshots**
No screenshot

**Logs**
```
I/flutter (31156): Writing to file :/data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/0000.png
I/flutter (31156): Writing to file :/data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/0001.png
I/flutter (31156): Writing to file :/data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/0002.png
I/flutter (31156): Writing to file :/data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/0003.png
I/flutter (31156): Writing to file :/data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/0004.png
I/flutter (31156): Writing to file :/data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/0005.png
I/flutter (31156): Writing to file :/data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/0006.png
I/flutter (31156): Writing to file :/data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/0007.png
I/flutter (31156): Writing to file :/data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/0008.png
I/flutter (31156): Writing to file :/data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/0009.png
I/flutter (31156): Writing to file :/data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/0010.png
I/flutter (31156): Writing to file :/data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/0011.png
I/flutter (31156): Writing to file :/data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/0012.png
D/flutter-ffmpeg(31156): Running FFmpeg with arguments: [-r, 25, -f, image2, -s, 1920x1080, -i, /data/user/0/com.lifelapse.life_lapse/app_flutter/17-03-2020 1:7:55/%04d.png, -vcodec, libx264, -crf, 25, -pix_fmt, yuv420p, 17-03-2020 1:7:55/test.mp4].
I/mobile-ffmpeg(31156): Loading mobile-ffmpeg.
E/AndroidRuntime(31156): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(31156): Process: com.lifelapse.life_lapse, PID: 31156
E/AndroidRuntime(31156): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(31156): 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
E/AndroidRuntime(31156): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(31156): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(31156): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(31156): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime(31156): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(31156): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(31156): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(31156): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found
E/AndroidRuntime(31156): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
E/AndroidRuntime(31156): 	at java.lang.System.loadLibrary(System.java:1669)
E/AndroidRuntime(31156): 	at com.arthenica.mobileffmpeg.Config.<clinit>(Config.java:131)
E/AndroidRuntime(31156): 	at com.arthenica.mobileffmpeg.Config.nativeFFmpegExecute(Native Method)
E/AndroidRuntime(31156): 	at com.arthenica.mobileffmpeg.FFmpeg.execute(FFmpeg.java:56)
E/AndroidRuntime(31156): 	at com.arthenica.flutter.ffmpeg.FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.doInBackground(FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.java:56)
E/AndroidRuntime(31156): 	at com.arthenica.flutter.ffmpeg.FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.doInBackground(FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.java:38)
E/AndroidRuntime(31156): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime(31156): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(31156): 	... 4 more
I/Process (31156): Sending signal. PID: 31156 SIG: 9
Lost connection to device.e.
```

**Environment**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Other**
thanks for the great work

**Comment by MalcolmMielle** [comment]
I saved my images as png but they were jpg -_- Sorry for the noise
