### ISSUE TITLE
Crash java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by lifenautjoe** [tanersener/flutter-ffmpeg#251]
## Description
Flutter ffmpeg crashes on Android 11 when executed.

On our app, after picking a video, the video gets passed through flutter ffmpeg with the following code.

```dart
  Future<File> compressVideo(File video) async {
    File resultFile;

    final FlutterFFmpeg _flutterFFmpeg = new FlutterFFmpeg();

    String resultFileName = 'compressed_video_' + _uuid.v4() + '.mp4';
    final path = await _getTempPath();
    final String resultFilePath = '$path/$resultFileName';

    int exitCode = await _flutterFFmpeg.execute(
        '-i ${video.path} -filter:v scale=720:-2 -vcodec libx264 -crf 23 -preset veryfast ${resultFilePath}');

    if (exitCode == 0) {
      resultFile = File(resultFilePath);
    } else {
      debugPrint('Failed to compress video, using original file');
      resultFile = video;
    }

    return resultFile;
  }
```

After upgrading to latest flutter stable version, we are getting a crash on Android 11 devices when this flutter ffmpeg command gets executed.

## Expected behavior

No crash to happen

## Current behavior

Crashes inmediately at the native level, exception doesn't get catch by flutter and thus not reported

## Demo

https://user-images.githubusercontent.com/12737509/105634220-4525b280-5e5d-11eb-8b87-5ee72b4f4aad.mp4

## Logs

Captured at the android native level 

````
java.lang.RuntimeException: 
  at android.os.AsyncTask$4.done (AsyncTask.java:399)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:252)
  at java.util.concurrent.FutureTask.run (FutureTask.java:271)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:929)
Caused by: java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1071)
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1007)
  at java.lang.System.loadLibrary (System.java:1668)
  at com.arthenica.mobileffmpeg.Config.<clinit> (Config.java:148)
  at com.arthenica.mobileffmpeg.Config.closeFFmpegPipe (Config.java)
  at com.arthenica.mobileffmpeg.Config.disableRedirection (Config.java)
  at com.arthenica.mobileffmpeg.Config.enableLogCallback (Config.java)
  at com.arthenica.mobileffmpeg.Config.enableStatisticsCallback (Config.java)
  at com.arthenica.mobileffmpeg.Config.ffmpegExecute (Config.java)
  at com.arthenica.mobileffmpeg.Config.registerNewFFmpegPipe (Config.java)
  at com.arthenica.mobileffmpeg.Config.setEnvironmentVariable (Config.java)
  at com.arthenica.mobileffmpeg.Config.setFontDirectory (Config.java)
  at com.arthenica.mobileffmpeg.Config.setLastReturnCode (Config.java)
  at com.arthenica.mobileffmpeg.Config.setLogLevel (Config.java)
  at com.arthenica.mobileffmpeg.FFmpeg.b (FFmpeg.java:2)
  at com.arthenica.flutter.ffmpeg.FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.a (FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.java:31)
  at com.arthenica.flutter.ffmpeg.FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.doInBackground (FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.java:2)
  at android.os.AsyncTask$3.call (AsyncTask.java:378)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:929)
````

## Environment

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B5012d darwin-x64, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[!] Connected device
    ! No devices available
```

**Comment by tanersener** [comment]
There are other issues reported regarding `UnsatisfiedLinkError`. Have you looked at them?

**Comment by lifenautjoe** [comment]
I have. Actually, expanding on the exception its

```
    --------- beginning of crash
2021-01-24 17:23:52.239 1399-1958/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    Process: social.openbook.app, PID: 1399
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:318)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/social.openbook.app-1/split_config.arm64_v8a.apk!/lib/arm64-v8a/libmobileffmpeg.so": 0
        at java.lang.Runtime.loadLibrary0(Runtime.java:977)
        at java.lang.System.loadLibrary(System.java:1530)
        at com.arthenica.mobileffmpeg.Config.<clinit>()
        at com.arthenica.mobileffmpeg.Config.a()
        at com.arthenica.mobileffmpeg.d.b()
        at c.a.a.a.a.a()
        at c.a.a.a.a.doInBackground()
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```

Which is the same as https://github.com/tanersener/flutter-ffmpeg/issues/237

I will close this issue to follow up on that one.
