### ISSUE TITLE
App Crashes on APK Release & iOS

### ISSUE THREAD

**Issue by EidarousDev** [tanersener/flutter-ffmpeg#257]
**Description**
App crashes on a specific page on `flutter build apk`
The app is working on Android on Debug mode(only) with no errors in the logcat/terminal. But when I tested it on iOS (even in debug mode), it crashes on a specific page. After long tests, I could know that this line was causing the app to crash.

**Expected behavior**
The page is expected to work without a crash!

**Current behavior**
App crashes when initializing that constructor
`FlutterFFmpegConfig _flutterFFmpegConfig = FlutterFFmpegConfig();`
When I dug deeper into that constructor
```
FlutterFFmpegConfig() {
    logCallback = null;
    statisticsCallback = null;

    print("Loading flutter-ffmpeg.");

    _eventChannel.receiveBroadcastStream().listen(_onEvent, onError: _onError);

    enableLogs();
    enableStatistics();
    enableRedirection();

    getPlatform().then((name) => print("Loaded flutter-ffmpeg-$name."));
  }
```
I found out that when I comment this line 
`//enableStatistics();`
the app doesn't crash, but since my code later on depends on this function (reading stats) and using `_flutterFFprobe.getMediaInformation(filePath);`

**Screenshots**
App crashes.

**Logs**
```
2021-02-08 01:34:39.688 7967-7967/? E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/com.devyat.alhani-2/lib/arm64/libmobileffmpeg.so": 0
        at java.lang.Runtime.loadLibrary0(Runtime.java:977)
        at java.lang.System.loadLibrary(System.java:1530)
        at com.arthenica.mobileffmpeg.Config.<clinit>()
        at com.arthenica.mobileffmpeg.Config.a()
        at c.b.a.a.d.a()
        at f.a.c.a.j$a.a()
        at io.flutter.embedding.engine.e.b.a()
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage()
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:328)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:6368)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
2021-02-08 01:34:39.688 7967-7967/? A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env). 
```

**Environment**
Flutter doctor output
```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality. // This can't be true cause it's definitely installed
    X Dart plugin not installed; this adds Dart specific functionality. // This can't be true cause it's definitely installed
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Other**
I'm using flutter_ffmpeg: ^0.3.0 in pubspec.yaml, and full-gpl package is set in android\build.gradle
`ext {
    flutterFFmpegPackage  = "full-gpl"
}`

Related package initializations code snippet:
```
final FlutterFFmpegConfig _flutterFFmpegConfig = new FlutterFFmpegConfig();
final FlutterFFmpeg _flutterFFmpeg = new FlutterFFmpeg();
final FlutterFFprobe _flutterFFprobe = new FlutterFFprobe();
```

**Comment by tanersener** [comment]
I'm reading your post but I don't get on which platform you get this error. Your message starts with Android debug mode, then you mention about a crash on iOS, but your logs include an Android stack trace. 

If you have an issue on Android release mode please see [Tips](https://github.com/tanersener/flutter-ffmpeg#5-tips) and #237. 

If this is an issue about iOS please provide logs from iOS platform.

**Comment by ming0520** [comment]
I have the same problem

**Comment by kamalgayan** [comment]
I faced the same issue. I fix this by following this steps -->

1.Make targetSdkVersion to 28

if still not worked than try this steps

1.under app level build gradle add this

    android {
        packagingOptions {
            pickFirst 'lib/x86/libc++_shared.so'
            pickFirst 'lib/x86_64/libc++_shared.so'
            pickFirst 'lib/armeabi-v7a/libc++_shared.so'
            pickFirst 'lib/arm64-v8a/libc++_shared.so'
        }
    }
2.Add this to your proguard-rules.pro -->

   -keep class com.arthenica.mobileffmpeg.Config {
         native <methods>;
         void log(int, byte[]);
         void statistics(int, float, float, long , int, double, double);
     }
