### ISSUE TITLE
Flutter 1.22.5 & flutter_ffmpeg 0.3.1 : Attempted to register plugin but it was already registered

### ISSUE THREAD

**Issue by lwinged** [tanersener/flutter-ffmpeg#322]
Hello @tanersener,

It seems that the way to install a plugin is incorrect. It provokes a crash.

Thank you for your help

```
Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@61e09bc) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@5299d45).
E/AndroidRuntime(20098): FATAL EXCEPTION: main
E/AndroidRuntime(20098): Process: com.ovaom.soundexplorer.dev, PID: 20098
E/AndroidRuntime(20098): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ovaom.soundexplorer.dev/com.example.sound_explorer.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/AndroidRuntime(20098): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3556)
E/AndroidRuntime(20098): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703)
E/AndroidRuntime(20098): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(20098): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(20098): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(20098): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
E/AndroidRuntime(20098): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(20098): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(20098): 	at android.app.ActivityThread.main(ActivityThread.java:7948)
E/AndroidRuntime(20098): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20098): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(20098): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/AndroidRuntime(20098): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/AndroidRuntime(20098): 	at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:119)
E/AndroidRuntime(20098): 	at com.arthenica.flutter.ffmpeg.FlutterFFmpegPlugin.registerWith(FlutterFFmpegPlugin.java:105)
E/AndroidRuntime(20098): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:18)
E/AndroidRuntime(20098): 	at com.example.sound_explorer.MainActivity.configureFlutterEngine(MainActivity.kt:18)
E/AndroidRuntime(20098): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:181)
E/AndroidRuntime(20098): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
E/AndroidRuntime(20098): 	at android.app.Activity.performCreate(Activity.java:7955)
E/AndroidRuntime(20098): 	at android.app.Activity.performCreate(Activity.java:7944)
E/AndroidRuntime(20098): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
E/AndroidRuntime(20098): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3531)
E/AndroidRuntime(20098): 	... 11 more
```

```
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
      // INCORRECT
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
com.arthenica.flutter.ffmpeg.FlutterFFmpegPlugin.registerWith(shimPluginRegistry.registrarFor("com.arthenica.flutter.ffmpeg.FlutterFFmpegPlugin"));
    // CORRECT
    flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
  }
}
```

I register manually a custom plugin

```
class MainActivity: FlutterActivity() {

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
      // My plugin
        val shimPluginRegistry = ShimPluginRegistry(flutterEngine)
        KotlinFlutterLibpdPlugin.registerWith(shimPluginRegistry.registrarFor(KotlinFlutterLibpdPlugin::class.simpleName))
        
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }

```

**Comment by tanersener** [comment]
Unfortunately `flutter_ffmpeg` doesn't support registering the plugin in that way. Why don't you allow `flutter` to install the plugin automatically. Is there a specific reason not to do that?
