### ISSUE TITLE
flutter master branch breaks flutter-ffmpeg entirely

### ISSUE THREAD

**Issue by lifenautjoe** [tanersener/flutter-ffmpeg#72]
**Description**

A new build system landed in master.

1. flutter ugprade on branch master
2. run flutter build ios
3. Receive warning that the Podfile is out of date. To remove it and let flutter rebuild it.
4. Remove Podfile
5. Reintegrate config related to flutter-ffmpeg with new syntax on newly generated Podfile

```
    if name == 'flutter_ffmpeg'
        pod name +'/full-gpl-lts', :path => File.join(symlink, 'ios')
    else
        pod name, :path => File.join(symlink, 'ios')
    end
```

6. Run flutter build ios again
7. Watch the build fail due to name duplicates on flutter-ffmpeg

```
      - Running pre install hooks
    [!] The 'Pods-Runner' target has frameworks with conflicting names: mobileffmpeg.framework, libavcodec.framework,
    libavdevice.framework, libavfilter.framework, libavformat.framework, libavutil.framework, libswresample.framework,
    libswscale.framework, gmp.framework, gnutls.framework, libcharset.framework, libhogweed.framework, libiconv.framework,
    and libnettle.framework.

    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/target_validator.rb:64:in
    `verify_no_duplicate_names'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/target_validator.rb:51:in
    `block (2 levels) in verify_no_duplicate_framework_and_library_names'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/target_validator.rb:45:in
    `each'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/target_validator.rb:45:in
    `block in verify_no_duplicate_framework_and_library_names'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/target_validator.rb:44:in
    `each'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/target_validator.rb:44:in
    `verify_no_duplicate_framework_and_library_names'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/target_validator.rb:35:in
    `validate!'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:578:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:158:in `install!'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/bin/pod:22:in `<main>'
```

**Expected behavior**
The build works

**Current behavior**
The build fails

**Logs**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.151, on Mac OS X 10.14.6 18G95, locale en-NL)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by lifenautjoe** [comment]
When trying to build through Xcode I also get the following

```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_MobileFFmpegConfig", referenced from:
      objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
      objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
  "_OBJC_CLASS_$_MobileFFmpeg", referenced from:
      objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
      objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
  "_OBJC_CLASS_$_ArchDetect", referenced from:
      objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
      objc-class-ref in flutter_ffmpeg(FlutterFfmpegPlugin.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by lifenautjoe** [comment]
Trying to do 
```
pod install
```

errors with the same conflicting names error

```
~/Documents/code/okuna/okuna-app/ios(release/0.0.55 ✗) pod install
Analyzing dependencies
Fetching podspec for `Flutter` from `Flutter`
Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
Fetching podspec for `file_picker` from `.symlinks/plugins/file_picker/ios`
Fetching podspec for `flutter_ffmpeg` from `.symlinks/plugins/flutter_ffmpeg/ios`
Fetching podspec for `flutter_image_compress` from `.symlinks/plugins/flutter_image_compress/ios`
Fetching podspec for `flutter_secure_storage` from `.symlinks/plugins/flutter_secure_storage/ios`
Fetching podspec for `image_cropper` from `.symlinks/plugins/image_cropper/ios`
Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
Fetching podspec for `intercom_flutter` from `.symlinks/plugins/intercom_flutter/ios`
Fetching podspec for `onesignal_flutter` from `.symlinks/plugins/onesignal_flutter/ios`
Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
Fetching podspec for `screen` from `.symlinks/plugins/screen/ios`
Fetching podspec for `share` from `.symlinks/plugins/share/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
Fetching podspec for `uni_links` from `.symlinks/plugins/uni_links/ios`
Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`
Fetching podspec for `video_thumbnail` from `.symlinks/plugins/video_thumbnail/ios`
Fetching podspec for `wakelock` from `.symlinks/plugins/wakelock/ios`
Downloading dependencies
Using FMDB (2.7.5)
Using Flutter (1.0.0)
Using Intercom (5.5.1)
Using Mantle (2.1.0)
Using OneSignal (2.11.0)
Using Reachability (3.2)
Using TOCropViewController (2.5.1)
Using VIMediaCache (0.4)
Using connectivity (0.0.1)
Using device_info (0.0.1)
Using file_picker (0.0.1)
Installing flutter_ffmpeg 0.2.7
Using flutter_image_compress (0.0.1)
Using flutter_secure_storage (3.3.1)
Using image_cropper (0.0.1)
Using image_picker (0.0.1)
Using intercom_flutter (1.0.7)
Using libwebp (1.0.3)
Installing mobile-ffmpeg-full-gpl (4.2.2.LTS)
Using mobile-ffmpeg-https (4.2.2)
Using onesignal_flutter (2.1.0)
Using package_info (0.0.1)
Using path_provider (0.0.1)
Using screen (0.0.1)
Using share (0.5.2)
Using shared_preferences (0.0.1)
Using sqflite (0.0.1)
Using uni_links (0.0.1)
Using url_launcher (0.0.1)
Using video_player (0.0.1)
Using video_thumbnail (0.0.1)
Using wakelock (0.0.1)
[!] The 'Pods-Runner' target has frameworks with conflicting names: mobileffmpeg.framework, libavcodec.framework, libavdevice.framework, libavfilter.framework, libavformat.framework, libavutil.framework, libswresample.framework, libswscale.framework, gmp.framework, gnutls.framework, libcharset.framework, libhogweed.framework, libiconv.framework, and libnettle.framework.
```

**Comment by lifenautjoe** [comment]
Solved the pod install issue. 

The following line was twice in the Podfile.
```
pod name, :path => File.join(symlink, 'ios')
```

Now having other errors which I thought were related to the LTS, but building with it does not fix it.


```
   duplicate symbol '_OBJC_CLASS_$_PodsDummy_flutter_ffmpeg' in:
        /Users/lifenautjoe/Documents/code/okuna/okuna-app/build/ios/Release-production-iphoneos/flutter_ffmpeg/flutter_ffmpeg
        .framework/flutter_ffmpeg(flutter_ffmpeg-dummy.o)
    duplicate symbol '_OBJC_METACLASS_$_PodsDummy_flutter_ffmpeg' in:
        /Users/lifenautjoe/Documents/code/okuna/okuna-app/build/ios/Release-production-iphoneos/flutter_ffmpeg/flutter_ffmpeg
        .framework/flutter_ffmpeg(flutter_ffmpeg-dummy.o)
    duplicate symbol '_OBJC_CLASS_$_FlutterFFmpegPlugin' in:
        /Users/lifenautjoe/Documents/code/okuna/okuna-app/build/ios/Release-production-iphoneos/flutter_ffmpeg/flutter_ffmpeg
        .framework/flutter_ffmpeg(FlutterFfmpegPlugin.o)
    duplicate symbol '_OBJC_METACLASS_$_FlutterFFmpegPlugin' in:
        /Users/lifenautjoe/Documents/code/okuna/okuna-app/build/ios/Release-production-iphoneos/flutter_ffmpeg/flutter_ffmpeg
        .framework/flutter_ffmpeg(FlutterFfmpegPlugin.o)
    duplicate symbol '_OBJC_IVAR_$_FlutterFFmpegPlugin._eventSink' in:
        /Users/lifenautjoe/Documents/code/okuna/okuna-app/build/ios/Release-production-iphoneos/flutter_ffmpeg/flutter_ffmpeg
        .framework/flutter_ffmpeg(FlutterFfmpegPlugin.o)
    ld: 5 duplicate symbols for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by lifenautjoe** [comment]
Turns out it was an issue due to the new system using `use_frameworks` always. Not related to the lib.

**Comment by tanersener** [comment]
Great, please let me know if you still have an issue about it.

**Comment by 2534290808** [comment]
I had the same problem

**Comment by tanersener** [comment]
@2534290808 Does the issue you reported in #82 include that problem?
